#!/bin/bash
### BEGIN INIT INFO
# Provides:          foodbox_service
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Foodbox service init.d script
# Description:       Foodbox service init.d script
### END INIT INFO


#!/usr/bin/env python

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

PRINTOUT=/home/pi/foodbox_device/service_script_log.txt

WORK_DIR=/home/pi/foodbox_device
PYTHON_FILE=src/main.py
HUB_ADDR_FILE=dat/hub_addr.dat
DEV_ID_FILE=dat/dev_id.dat
BATTERY_BUS=dat/hwconfig/battery_bus.dat
BATTERY_ADDR=dat/hwconfig/battery_addr.dat
BATTERY_FUNC=dat/hwconfig/battery_func.dat

BATTERY_SCRIPT=foodbox_batterycheck.sh
COMM_SCRIPT=foodbox_commcheck.sh
STOP_SCRIPT=foodbox_stop.sh

DIR=/home/pi/foodbox_device
DAEMON=$WORK_DIR/$PYTHON_FILE
DAEMON_NAME=foodbox_service
DAEMON_OPT=""
DAEMON_USER=pi
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start(){
    cd $WORK_DIR
    NOW="Service Script Start...[`date -d "0 days"`]"
    echo $NOW >> $PRINTOUT
    bash $BATTERY_SCRIPT $BATTERY_BUS $BATTERY_ADDR $BATTERY_FUNC >> $PRINTOUT
    if [ 1 -eq $? ]; then
        echo "BATTERY REMAINS UNDER 25%" >> $PRINTOUT
        poweroff
    fi
    echo "BATTERY REMAINS OVER 25%... LET'S CHECK THE NETWORK STATUS" >> $PRINTOUT
    bash $COMM_SCRIPT $HUB_ADDR_FILE $DEV_ID_FILE >> $PRINTOUT
    if [ $? -eq 0 ]; then
        sudo chmod 755 $PYTHON_FILE
        sudo nice -n -10 ./$PYTHON_FILE >> $PRINTOUT &
        exit 0
        #log_daemon_msg "Starting system $DAEMON_NAME daemon"
        #start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
        #RES=$?
        #echo Result : $RES >> $PRINTOUT
        #log_end_msg $RES
    fi
    
}

do_stop(){
    cd $WORK_DIR
    #log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    #start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    #log_end_msg $?
    pid=$(ps aux | grep $PYTHON_FILE | grep python | awk '{print $2}')
    if [ -n "$pid" ]; then
        red='dat/hwconfig/pin_red.dat'
        green='dat/hwconfig/pin_green.dat'
        blue='dat/hwconfig/pin_blue.dat'
        led='dat/hwconfig/pin_led.dat'

        red=$(cat $red)
        green=$(cat $green)
        blue=$(cat $blue)
        led=$(cat $led)

        gpio -g mode $red output
        gpio -g mode $green output
        gpio -g mode $blue output
        gpio -g mode $led output

        gpio -g write $red 0
        gpio -g write $green 0
        gpio -g write $blue 0
        gpio -g write $led 0
        sudo kill -9 $pid
    fi
}

case "$1" in
    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0